### ISSUE TITLE
Story: Ansible content collections support in Galaxy

### ISSUE THREAD

**Issue by cutwater** [ansible/galaxy#1524]
Implement support of importing and managing Ansible Content Collections in Galaxy.

Tasks:

- [ ] Data model implementation (#1525).
- [ ] API endpoint for search against collections and repositories (#1526).
- [x] Implement worker tasks to import collections (#1527).
- [x] Implement collections support in importer (#1528).
- [x] Move quality score calculation to importer (#1529).
