### ISSUE TITLE
Collections: Implement API v2 endpoints

### ISSUE THREAD

**Issue by cutwater** [ansible/galaxy#1661]
Implement required API endpoints for collections according to the #1653 

### Action items:

- [x] Implement collection import task detail endpoint #1662
- [x] Collection detail API endpoint #1727
- [x] Collection version list API endpoint #1728
- [x] Artifact download API endpoint #1744
