### ISSUE TITLE
Namespace refactor

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#243]
### Summary

The overall point of the task is to future-proof the data model to accommodate the following things we know we will be implementing in the future:

- A 'partner' designation
- Other designations besides 'partner', or perhaps even levels of 'partners'
- Consuming content from multiple SCMs, not just GitHub

### Key concepts 
- Namespace will be unique to Galaxy. Every user will map to at least 1 namespace.
- Many Provider (i.e., GitHub, GitLab, Atlassian, etc.) Namespaces will map to a Namespace.
- A given Provider Namespace can only map to one Namespace.
- A Namespace is not a 'partner'. 'Namespace' and 'partner' are two separate concepts.
- In the future, a Namespace may be designated as a 'partner' by simply turning a Namespace attribute on or off.
- We don't know today who or what a 'partner' is.
- We do know we need to deliver content by Namespace.Repository_Name.Content_Name.
- Because of wanting to deliver content based on Namespace, and not Provider_Namespace, every Provider_Namespace needs to map to Namespace, as stated above..

We're allowing users to create a Namespace for the following reasons:

- Namespace does not hold any special meaning. As mentioned above, a Namespace is not automatically a 'partner'.
- A Namespace creates a nice mechanism for anyone to have a public Profile within Galaxy that is completely separate from their Provider Profile(s)
- A Namespace allows everyone the ability to aggregate their content repositories from multiple Providers and Provider Namespaces under a single Galaxy Namespace.

### Task Work 

We'll know this task is complete when the following items are complete:

- [x] Create new models: Namespace, Provider
- [x] Change the existing Namespace model to `Provider_Namespace`. `Provider_Namespace` is simply a one-to-one with a GitHub (or any future SCM) namespace. In GitHub, a namespace can be a username (e.g., geerlingguy), or an Organization (e.g., Ansible).
- [x] The combination of Provider and Name is unique within the `Provider_Namespace` model.
- [x] There is a one-to-many relationship from Provider to Provider_Namespace. A Namespace can have many Provider_Namespaces, but a given Provider_Namespace can only belong to a single Namespace.
- [x] There is a many-to-many relationship between User and Namespace. A user can own many Namespaces, and a Namespace can belong to many users.
- [x] A namespace matching the user's username will automatically be created for a user the first time they login.
- [x] A user can create a Namespace. (This means that Namespaces are created on a first-come-first-serve basis).
- [x] A user can add other users as owners (i.e., admins) of a given Namespace.
- [x] Users can associate any of their Provider_Namespaces to their Namespaces. As stated above, the API and UI must enforce the notion that a Provider_Namespace can only belong to a single Namespace.
- [x] Users can update the profile information for a Namespace
- [x] Populate the Namespace table with the existing Provider_Namespace values, such that there will initially be in the data a one-to-one mapping from Namespace to Provider_Namespace, and make the correct user association to Namespace. For example, today, we have a Namespace row for 'geerlingguy'. After the data migration, there will be a row in Namespace for 'geerlingguy', and it will be associated with the 'geerlingguy' row in the Provider_Namespace table. The Namespace row for 'geerlingguy' will be associated with the 'geerlingguy' user account.

**Comment by cutwater** [comment]
> During creation of a new top-level Galaxy namespace, the process will make an API call to GitHub and check to see if the new name matches an existing GitHub organization name. If it does, the user must already be part of the GitHub organization. For example, if attempting to create an 'ansible' top-level namespace, the user must be part of the GitHub 'ansible' organization within GitHub.

This change makes our ACL model bound to GitHub, doesn't it? How does it correspond with our plans of adding GitLab support in a future and being hosting-agnostic?

**Comment by chouseknecht** [comment]
Rather than checking GitHub for an existing organization, and validating that the user is part of it, Galaxy namespaces will be reserved on a 'first-come-first-serve' basis. Our Terms of Service will need to cover the possibility of someone reserving a trademarked or copyrighted name, and what actions we might take in that circumstance.

**Comment by gregdek** [comment]
So when you say:

"Change Galaxy namespace to be a one-to-many mapping to GitHub namespaces"

I thought the idea was to create a new namespace that was independent of current Galaxy namespaces, for the specific purpose of vendor aggregation.

**Comment by alikins** [comment]
>  The combination of top-level Galaxy namespace and content name will be unique.    


What is an example of a 'content name'? 


> This change makes our ACL model bound to GitHub, doesn't it? How does it correspond with our plans of adding GitLab support in a future and being hosting-agnostic?

> associate one or more GitHub namespaces to each Galaxy namespace,

If Galaxy namespace -> Github namespace is one-to-many:
-  is  github namespaces -> Galaxy namespaces many-to-one or many-to-many? 
- Can multiple galaxy namespaces be associated to 'github.com/alikins' ?



Is content name referring to the galaxy equiv of a project?
ie, for a current existing role 'alikins.yet-another-epel' from the github repo github.com/alikins/yet-another-epel:
-  is 'yet-another-epel' the content name or is the content name the new galaxy name under my galaxy namespace?
- (and could the galaxy content name be different than the github project name?)

if I created 'alikins_awesome' galaxy namespace:
 -  I could associate github.com/alikins to the 'alikins_awesome' galaxy namespace?
If on galaxy I create a 'the-best-epel' under 'alikins_awesome':
  - I can further specifically associate 'alikins_awesome.the-best-epel' to github.com/alikins/yet-another-epel (more or less an alias...)?

**Comment by cutwater** [comment]
> I thought the idea was to create a new namespace that was independent of current Galaxy namespaces, for the specific purpose of vendor aggregation.

It looks quite similar to what GitHub or GitLab achieve with organizations and groups respectively. Namespaces are unique across users and orgs, so we need to allow users to create sub-namespaces that can include multiple repos.

### Actual data model

```
User -> User Namespace -> GitHub Repository
```

### Proposed data model

```
User
    -> User Namespace
        -> GitHub Repository | Multiple Repositories
    ->> Multiple Namespaces
         ->> Multiple Repositories
```

@chouseknecht Please correct me if I'm wrong.

**Comment by chouseknecht** [comment]
Alex and I worked through this today, and below is an image of the model we came up with. Hopefully it explains it better than our text attempts.

![databasediagram](https://user-images.githubusercontent.com/1282865/33962170-a499235c-e01e-11e7-8bc2-15601d0e0017.png)

**Comment by abadger** [comment]
From a community perspective, I would make namespace owner a Many::Many.  I think a single owner for a namespace will become a bottleneck (mostly from an owner going awol when there are other people who are willing to take over).

**Comment by chouseknecht** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Namespace refactor](https://trello.com/c/veDsPZhi/6-namespace-refactor)
