### ISSUE TITLE
Index all Ansible content types found within a repository

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#245]
Roles can contain many modules and plugins, and Galaxy should recognize and index these content types.

#### Tasks

- [x] Modify the data model and search index to track modules and plugins
- [x] Modify the import process to read `/library`, `/<type>_plugins` directories
- [ ] ~~The import process should also recurse into the `/roles` directory, and index content found in any modules and plugins directories~~
- [ ] ~~Respect `.galaxy_ignore`~~
- [x] For each module and plugin, the process should also read and index the meta data contained in the file.
- [x] Update My Content to work with the new data model
- [x] Add 'branch' to repository settings on My Content

**Comment by chouseknecht** [comment]
### Data model
```
Namespace
    ->> Repository
            ->> modules
            ->> plugins, type (action, filter, callback, cache, etc.)
            ->> roles
```

### Example import:

```
acmeco
    ->> my_roles
        ->> modules (modulea, moduleb, modulec)
        ->> plugins (plugina, pluginb, pluginc)
        ->> roles (rolea, roleb)
```

### Example use cases: 

```
ansible-galaxy install acmeco.my_roles  

    -> install all content from the acmeco/my_roles repository
```

```
ansible-galaxy install --type role acmeco.my_roles  

    -> install all roles from the acmeco/my_roles repository
```

```
ansible-galaxy install --type module acmeco.my_roles.moduleb 

    -> install only moduleb from acmeco/my_roles repository
````

```
ansible-galaxy install --type module acmeco.moduleb
 
   -> install only module be from acmeco/my_roles repository
```

**Comment by chouseknecht** [comment]
## Dependencies

### Questions
- Where to specify module -> module_utils dependencies?
- Where to put module meta data (particularly dependencies), let's review with Toshio.

### Dependencies for a role

Will continue to live in meta/main.yml for a role

```
dependencies:
  roles:
    - acmeco.repo_name.role_name
  modules:
    - acmeco.repo_name.module_name
  plugins:
    - acmeco.repo_name.plugin_name
```

**Comment by maxamillion** [comment]
:+1:

**Comment by alikins** [comment]
> ### Data model
> ```
> Namespace
>     ->> Repository
>             ->> modules
>             ->> plugins, type (action, filter, callback, cache, etc.)
>             ->> roles
> ```
> 
> ### Example import:
> 
> ```
> acmeco
>     ->> my_repo
>         ->> modules (modulea, moduleb, modulec)
>         ->> plugins (plugina, pluginb, pluginc)
>         ->> roles (rolea, roleb)
> ```

Could we require/assume a 'common (or 'base' or 'shared' etc) role and move the otherwise associated
modules and plugins under it?

### Data model
```
Namespace
    ->> Repository
          ->> roles
                ->> modules
                ->> module_utils
                ->> plugins (action, filter, callback, cache, etc.)
                ->> other role stuff

```

### Example import:

```
acmeco
   ->> myrepo
        ->> roles
              ->> common
                    ->> modules
                    ->> module_utils
                    ->> plugins
                         ->> callback
                         (etc)
                    ->> vars
                    ->> tasks
                    (etc)
             ->> setup-epel
             ->> disable_selinux
             ->> devop_the_nagios_kubernetes_cloud_container_deploy
            (etc)
```

That might also answer the 'where does module_utils live?' question

**Comment by alikins** [comment]
> That might also answer the 'where does module_utils live?' question

Somewhat off this specific subject, but related to plugin/module installers would the idea of adding a 
'lib' dir/path to roles to allow plugins to bundle and share any needed python deps.

For plugins, the plugin loader could make sure whatever is in my_org/my_project/roles/my_role/lib/python/ gets added to the python path. Or more generically, make sure the python code there can be imported from the plugins by some means (normal sys.path tweaking, pip/egg stuff, python module import namespaces, zip imports, sys.metapath hackery, etc).

**Comment by chouseknecht** [comment]
The core team has agreed on the first iteration of a new repository *manifest* file, called `ansible-galaxy.yml`. 

The intention of the file is provide metadata to the Galaxy import process and the Galaxy client install. The metadata includes the types and paths of the content available in the repo, along with any dependencies. This new manifest file will exist in the root of the repository

**NOTE**: Dependencies are limited to Ansible content types. This specification does not include Python dependencies, or other non-Ansible content. Such dependencies may be included in future iterations.

More details and a sample are available on a public ethepad, please add your comments:

https://etherpad.net/p/Galaxy_Metadata

**Comment by chouseknecht** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Index all content types found within a repo](https://trello.com/c/aXZ8B3FN/5-index-all-content-types-found-within-a-repo)

**Comment by maxamillion** [comment]
It was brought up by @bcoca while discussing this in `#ansible-devel` on freenode that we already have a command line UX convention similar to this in the `ansible-doc` command for `ansible-doc -t <plugin_type>` and for the sake of consistency I'd like to propose the following:

### Example use cases: 

```
ansible-galaxy install acmeco.my_repo

    -> install all content from the acmeco/my_repo repository
```

```
ansible-galaxy install -t role acmeco.my_repo 

    -> install all roles from the acmeco/my_repo repository
```

```
ansible-galaxy install -t role acmeco.my_repo.role_name

   -> install a single role from acmeco/my_repo repository
```

```
ansible-galaxy install -t module acmeco.my_repo

    -> install all modules from acmeco/my_repo repository
````

```
ansible-galaxy install -t module acmeco.my_repo.moduleb 

    -> install only moduleb from acmeco/my_repo repository
````

```
ansible-galaxy install -t module_utils acmeco.my_repo.utila 

    -> install only utila from acmeco/my_repo repository
````

```
ansible-galaxy install -t action_plugin acmeco.my_repo.plugina 

    -> install only plugina from acmeco/my_repo repository
````

```
ansible-galaxy install -t filter_plugin acmeco.my_repo.filtera 

    -> install only filtera from acmeco/my_repo repository
````


I personally think the original suggestion by @chouseknecht is a nicer experience, but given the precedent I'd prefer consistency within the ansible command line.

Thoughts?

**Comment by chouseknecht** [comment]
@maxamillion 

I'm OK with with the changes you and @bcoca are proposing. Keeping the UI consistent makes sense.
